class FileNotFoundException(Exception):
    ...

class CannotLoadImageByOpencvException(Exception):
    ...

class IsNotAnImageException(Exception):
    ...

class InputMustBeAnInteger(Exception):
    ...